package-lock.json
package.json
prisma/schema.prisma

Create language table #19

---

.env.example
package-lock.json
package.json
prisma/schema.prisma
src/app.css
src/app.d.ts
src/hooks.server.ts
src/lib/auth.ts
src/lib/cookies_manager.ts
src/lib/database.ts
src/lib/nodemailer_manager.ts
src/locales/en.json
src/locales/ja.json
src/locales/km.json
src/locales/ko.json
src/locales/zh-TW.json
src/routes/+layout.server.ts
src/routes/+page.svelte
src/routes/init-db/+server.ts
src/routes/pin_code/+page.server.ts
src/routes/pin_code/+page.svelte
src/routes/sign_in/+page.server.ts
src/routes/sign_in/+page.svelte
src/routes/sign_out/+page.server.ts

[sveltekit-authentication-example](https://github.com/sinProject-Inc/sveltekit-authentication-example)を参考にPINコードでサインインできるようにした。
1. `.env.example`を参考に`GMAIL_USER` と`GMAIL_PASS` を追記
2. prisma db更新
https://user-images.githubusercontent.com/50548952/211969559-005408b8-4dc9-496c-80f9-25f6be92b2bb.mov
- 細かいデザイン
- 一部翻訳
- `.env` 追記によるREADMEの変更

Sign in by PIN code #141 

---

src/routes/api/add-translation/[text_id]/[language_code]/[translation]/+server.ts
src/routes/api/languages/+server.ts
src/routes/api/text/[language_code]/+server.ts
src/routes/api/translate-with-google-advanced-glossary/[text]/[target_lang_code]/[source_lang_code]/+server.ts
src/routes/sign-out/+page.server.ts

refactor: Use $lib for import path in routes/*

---

src/lib/components/translate/translate_box.svelte
src/lib/speech/speech_language_code.ts
src/lib/speech/text_to_speech_url.ts
src/locales/en.json
src/routes/+page.svelte
src/routes/translate/+page.svelte

translate: Save translate data #177

---

src/routes/init-db/+server.ts

Shorten displayed locale names on translate #227

---

src/lib/app.css
src/routes/+page.svelte

Make text fields easier to see #217

---

src/lib/components/translate/translate_box.svelte

style: /translate - Fix background color change on record / stop recording #183

---

src/routes/translate/+page.svelte

Show 100 texts in history #224

---

src/lib/components/translate/translate_box.svelte
src/routes/translate/+page.svelte

Set focus textarea on reload #211

---

src/routes/+page.svelte
src/routes/translate/+page.svelte

Prevent same languages #223

---

src/routes/+page.svelte

Make bottom section and speech list no longer overlap #220

---

src/routes/+page.svelte

Add more padding on the bottom panel on main #244

---

src/lib/components/confirm_delete_modal.svelte
src/lib/components/icons/check_icon.svelte
src/locales/ja.json

Adjust dialogue style #225

---

e2e/translate.spec.ts
src/lib/components/icon_button.svelte
src/lib/components/icons/swap_icon.svelte
src/lib/components/translate/translate_box.svelte
src/routes/translate/+page.svelte

Don't allow clicking on the top bar when listening (Translate) #230

---

e2e/translate.spec.ts

Fix capitalization of expected string in test "adding text should add it to the history" #252

---

src/lib/components/translate/translate_box.svelte
src/routes/+page.svelte
src/routes/translate/+page.svelte

Refactor: get select element value #265

---

src/lib/auth/pin_code_mailer.ts

Rewrite process.env #168

---

src/routes/translate/+page.server.ts

Remove unused variable 'languages' #256

---

src/lib/view/html.ts
src/lib/view/locale_select_element.ts
src/routes/+page.svelte
src/routes/translate/+page.svelte

Create LocaleSelectElement class #257

---

src/lib/components/translate/translate_box.svelte

Rearrange the order of variable declarations #268

---

src/routes/+page.svelte

Don't show 'selected' log on browser console #271

---

src/routes/+page.svelte
src/routes/translate/+page.svelte

Refactoring: Empty line adjustment #276

---

src/lib/components/translate/translate_box.svelte

Translate: When you start listening and stop without speaking, the browser should not generate an error #261

---

src/lib/components/translate/translate_box.svelte

Disable copy and delete icon when listening #250

---

src/lib/components/translate/translate_box.svelte

Refactor the disabling of icon buttons to use "enabled" property #251

---

src/lib/components/translate/translate_box.svelte

Don't call fetch API when clicking on a text in the history  #284

---

src/lib/components/text_list_text.svelte

Max width and overflow wrap break word on history #287

---

src/lib/components/translate/translate_box.svelte

 Fix text not being able to be played without pressing enter #267

---

src/lib/language/default_locales.ts
src/routes/+page.svelte
src/routes/translate/+page.svelte

Refactor translate screen #299

---

src/lib/components/snackbar.svelte

Copy notification is hidden #305

---

src/locales/es.json

Fix Spanish select_different_language #310

---

src/routes/init-db/+server.ts

Refactor what was pointed out in code climate #304

---

.vscode/settings.json
e2e/translate.spec.ts
src/lib/components/translate/translate_box.svelte

When there is no text, hide buttons #312

---

src/hooks.server.ts
src/lib/app/app.ts
src/lib/app/app_setting_repository.ts
src/lib/app/app_setting_repository_prisma.test.ts
src/lib/app/app_setting_repository_prisma.ts
src/lib/app/repository.ts
src/lib/auth/auth_pin_repository_prisma.ts
src/lib/auth/auth_token_repository_prisma.ts
src/lib/auth/life_time.ts
src/lib/auth/signing.ts
src/lib/auth/user_repository.ts
src/lib/auth/user_repository_prisma.ts
src/lib/language/language_repository_prisma.ts
src/lib/language/locale_repository_prisma.ts
src/lib/speech/sound/sound_repository.ts
src/lib/speech/sound/sound_repository_prisma.ts
src/lib/text/text_repository_prisma.ts
src/lib/translation/translation_repository.ts
src/lib/translation/translation_repository_prisma.ts
src/routes/api/add-text/[language_code]/[text]/+server.ts
src/routes/api/add-translation/[text_id]/[language_code]/[translation]/+server.ts
src/routes/api/delete-text/[text_id]/+server.ts
src/routes/api/find-translation/[text_id]/[language_code]/+server.ts
src/routes/api/languages/+server.ts
src/routes/api/locales/+server.ts
src/routes/api/text-to-speech/[text]/[locale_code]/+server.ts
src/routes/api/text/[language_code]/+server.ts
src/routes/init-db/+server.ts
src/routes/pin-code/+page.server.ts

Create repository interfaces #316 Refactor

---

src/lib/app/app_setting_repository.ts
src/lib/app/app_setting_repository_prisma.test.ts
src/lib/app/app_setting_repository_prisma.ts
src/lib/app/setting_key.ts
src/lib/auth/life_time.ts
src/lib/general/sentence_service.ts
src/lib/general/valid_key.ts
src/lib/speech/speech_element.ts
src/lib/speech/speech_text_area_element.ts
src/lib/speech/speech_text_element.ts
src/lib/speech/text_content.ts
src/lib/speech/web_speech_recognition.ts
src/routes/+page.svelte
src/routes/api/split-sentence/[text]/+server.ts
src/routes/translate/+page.svelte

Use value objects #321

---

src/routes/+page.svelte

Refactor main page to be like translate page #314

---

e2e/translate.spec.ts
src/lib/components/text_list_text.svelte
src/lib/components/translate/translate_box.svelte
src/lib/components/translate/translate_box_old.svelte
src/lib/speech/text_to_speech_url.ts
src/lib/translation/add_translation_api.ts
src/lib/view/event_key.ts
src/routes/+page.svelte
src/routes/translate-old/+page.server.ts
src/routes/translate-old/+page.svelte
src/routes/translate/+page.svelte

Refactor translate page #328

---

.vscode/extensions.json

Remove ardenivanov.svelte-intellisense extension from recommendations #233

---

src/lib/components/icon_button.svelte
src/routes/+page.svelte

Change background color of mic on main page when listening #254

---

src/routes/+page.svelte
src/routes/translate/+page.svelte

Refactor pages #326

---

src/lib/components/confirm_delete_modal.svelte

Fix: Translate: Make log scrollable even if deleted #333

---

src/lib/speech/text_to_speech_url.ts
src/routes/+page.svelte

Refactor TextToSpeechUrl class #325

---

.vscode/extensions.json
src/lib/speech/web_speech_recognition.ts
src/routes/pin-code/+page.server.ts
src/routes/sign-in/+page.server.ts
tsconfig.json

Update tsconfig.json #339

---

src/lib/components/text_list_text.svelte

Replace ternary operator with function in text_list_text #232

---

e2e/translate.spec.ts
src/lib/components/translate/translate_box_old.svelte
src/routes/html_old.ts
src/routes/pin-code/+page.server.ts

Change to strict equality operator #341

---

.vscode/extensions.json
package.json
vite.config.ts

Enable batch testing with Vitest #320

---

src/lib/components/translate/translate_box.svelte
src/lib/speech/web_speech_recognition.ts
src/routes/+page.svelte
src/routes/translate/+page.svelte

Fix: speech recognition onresult called twice on android #344

---

src/lib/api/api.ts
src/lib/api/api_path.test.ts
src/lib/api/api_path.ts
src/lib/speech/sound/sound_file_path.ts
src/lib/speech/text_to_speech_url.ts
src/lib/speech/voice/microsoft_voice.ts
src/lib/text/text_limit.ts

Tweak unnecessary code #354

---

src/routes/web-socket/+page.svelte

Chat: Validate inputs #362

---

src/routes/web-socket/+page.svelte

Chat: Show version on footer #366

---

.eslintrc.cjs
socket-handler.js
src/lib/chat/chat_entity.js
src/lib/chat/chat_message.js
src/lib/chat/chat_name.js

Rewrite eslintrc to eliminate svelte errors #374

---

prisma/schema.prisma
socket-handler.js
src/lib/chat/chat_entity.ts
src/routes/chat/+page.svelte

Chat: Show translated Log #377

---

.vscode/extensions.json

Add Tailwindcss to recommended extensions #381

---

src/lib/app.css
src/lib/speech/speech_div_element.ts
src/lib/view/event_key.ts
src/routes/+page.svelte
src/routes/chat/+page.svelte

Chat: Support voice input #376

---

e2e/example.spec.ts
playwright.config.ts
server.js
tests-examples/demo-todo-app.spec.ts
tests/test.ts

Format files #388

---

src/lib/view/web.ts
src/routes/chat/+page.svelte

Fix: Chat: Scroll to the bottom #399

---

src/routes/chat/+page.svelte

fix: notification #403

---

package.json
prisma/seed.ts
src/routes/init-db/+server.ts

Seeding the database on Prisma #410

---

.vscode/extensions.json

Add Live share to recommended extensions #414

---

src/routes/+page.svelte
src/routes/translate/+page.svelte

change add-translation access to get-transalation #413

---

.vscode/extensions.json

Add recommended extensions for highliting errors #425

---

.vscode/settings.json

Update workspace settings.json #427

---

src/lib/components/icons/loading_icon.svelte
src/routes/chat/+page.svelte

Show progress icon while sending message #392

---

.vscode/extensions.json
.vscode/settings.json
package-lock.json
package.json
rest/test.rest
rest/test.ts

Add recommended extensions #431

---

.gitignore
package-lock.json
package.json
prisma/seed.ts
server.ts
socket-handler.ts
src/lib/app/logger.ts
src/lib/auth/user_repository_prisma.ts
src/lib/speech/speech_by_microsoft.ts
src/lib/text/get_text_service.ts
src/lib/translation/deepl_translator.ts
src/lib/translation/get_translation_service.ts
src/lib/translation/translate_with_google_advanced.ts
src/lib/translation/translation_language_code.ts
src/routes/+page.server.ts
src/routes/api/add-text/[locale_code]/[text]/+server.ts
src/routes/api/add-translation/[text_id]/[locale_code]/[translation]/+server.ts
src/routes/api/create-glossary-on-google/+server.ts
src/routes/api/delete-text/[text_id]/+server.ts
src/routes/api/find-translation/[text_id]/[locale_code]/+server.ts
src/routes/api/get-translation/[text]/[source_locale_code]/[target_locale_code]/+server.ts
src/routes/api/split-sentence/[text]/+server.ts
src/routes/api/text-to-speech/[text]/[locale_code]/+server.ts
src/routes/api/text/[locale_code]/+server.ts
src/routes/api/translate-with-deepl/[text]/[target_locale_code]/+server.ts
src/routes/api/translate-with-google-advanced-glossary/[text]/[target_locale_code]/[source_locale_code]/+server.ts
src/routes/api/translate-with-google-advanced/[text]/[target_locale_code]/+server.ts
src/routes/api/translate-with-google-basic/[text]/[target_locale_code]/+server.ts
src/routes/pin-code/+page.server.ts

Output log file #429 output log by winston

---

server.ts
src/hooks.server.ts
src/lib/translation/deepl_translator.ts
src/routes/+page.server.ts

Catch uncaughtException #434

---

package-lock.json
src/routes/chat/+page.svelte

Auto leave on socket disconnected #444

---

.stylelintrc.json
package-lock.json
package.json
src/lib/app.css

Use stylelint #463

---

.vscode/settings.json

Acitivate icon theme on the workspace #466

---

playwright.config.ts

Run the local dev server before starting the playwright tests #468

---

.vscode/settings.json

disable editor minimap #471

---

.husky/pre-push
.vscode/settings.json
package.json
src/hooks.server.ts
src/lib/speech/web_speech_recognition.ts

Run typecheck #473

---

.vscode/extensions.json

Remove ardenivanov.svelte-intellisense extension from recommendations #476

---

.vscode/extensions.json

Add code runner to recommended extensions #480

---

.vscode/settings.json
README.md

Add code spell checker ignore paths #483

---

.husky/pre-push

Remove Playwright test from pre push #487

---

playwright.config.ts

Don't show playwright error report #488

---

src/routes/+page.svelte
src/routes/chat/+page.svelte
src/routes/pin-code/+page.svelte
src/routes/sign-in/+page.svelte
src/routes/translate/+page.svelte

Collect web front error logs #485 handle error all pages

---

package.json

Release v0.31.0 #498

---

nginx/nginx.conf
server/index.ts
server/socket-handler.ts
src/hooks.server.ts
src/lib/network/client_address.ts
src/lib/network/socket_client_address.ts
src/routes/+page.server.ts
src/routes/api/log/+server.ts
src/routes/chat/+page.server.ts
src/routes/translate/+page.server.ts

Get remote address via proxy #493

---

package.json

Release v0.32.0 #504

---

.vscode/settings.json
src/lib/app.css
src/lib/components/navbar.svelte
src/lib/view/urlify.ts
src/routes/chat/+page.svelte

Allow linking in chat #507

---

prisma/schema.prisma
server/socket-handler.ts
src/lib/chat/chat.ts
src/lib/chat/chat_member_repository_prisma.ts
src/lib/components/icons/desktop_windows_icon.svelte
src/lib/components/icons/phone_android_icon.svelte
src/lib/view/web.ts
src/routes/chat/+page.svelte

Show device icon #511

---

.husky/pre-push
src/lib/auth/life_time.test.ts

fix pre-push #523

---

src/routes/pin-code/+page.server.ts

Check mail address pattern on back-end #452

---

nginx/nginx.conf
src/lib/view/urlify.ts

Pass websocket communication with nginx #532

---

server/socket-handler.ts

Kill ghost websocket connection #531

---

package.json

Update version to v0.33.0 #528

---

src/lib/auth/pin_code_mailer.ts
src/routes/pin-code/+page.server.ts

Change email title #515

---

src/routes/chat/+page.svelte

Chat: add transitions #543

---

server/socket-handler.ts
src/routes/chat/+page.svelte

Chat: confirm transmission completion #545

---

package-lock.json
package.json

Update version to v0.34.0 #547

---

.eslintrc.cjs

Check console log on pre-commit #554

---

.eslintrc.cjs
rest/test.ts
server/index.ts
src/hooks.server.ts
src/lib/components/text_list_text.svelte
src/lib/components/translate/translate_box.svelte
src/lib/speech/text_to_speech_url.ts
src/lib/view/log/web_logger.ts
src/routes/+page.svelte
src/routes/chat/+page.svelte
src/routes/pin-code/+page.svelte
src/routes/translate/+page.svelte

Strengthen lint checks #556

---

src/lib/components/icon_button.svelte
src/lib/components/text_list_text.svelte
src/lib/components/translate/translate_box.svelte
src/routes/+page.svelte
src/routes/chat/+page.svelte
src/routes/translate/+page.svelte

Receiving the on click event simply in a custom component #560

---

src/routes/pin-code/+page.svelte
src/routes/sign-in/+page.svelte

Fix Sign in behavior #566

---

e2e/translate.spec.ts
rest/test.rest
src/lib/text/text_limit.ts
src/lib/text/texts_api.ts
src/params/text_limit.ts
src/routes/+page.svelte
src/routes/api/text/[locale_code=locale_code]/[[text_limit=text_limit]]/+server.ts
src/routes/translate/+page.svelte

Use optional parameters #573

---

README.md

Readme を更新する #578

---

.github/workflows/ci.yml

Make CI logs downloadable #584

---

.github/workflows/ci.yml
.husky/pre-push
e2e/auth.setup.ts
e2e/translate.spec.ts

Exec playwright test and build on push #598

---

README.md
docs/10-getting-started/20-creating-a-project.md
src/lib/app.css
src/routes/docs/[slug]/+page.svelte

Docs: add list style #609

---

src/lib/app.css
src/lib/components/navbar.svelte
src/routes/docs/[slug]/+page.svelte
src/routes/docs/[slug]/OnThisPage.svelte

Docs: fix section link area #608

---

docs/10-getting-started/20-creating-a-project.md
src/lib/app.css
src/lib/docs/markdown.ts
src/routes/docs/[slug]/OnThisPage.svelte

Section tree on this page #613

---

src/routes/+layout.svelte

Change background on navigation #595

---

src/routes/+layout.svelte

Rename interval_id #616

---

docs/10-getting-started/20-creating-a-project.md
src/lib/app.css
src/routes/docs/[slug]/+page.svelte
src/routes/docs/[slug]/OnThisPage.svelte

Docs: add ol-li style #618

---

docs/10-getting-started/30-project-structure.md
src/lib/app.css
src/routes/docs/[slug]/+page.svelte

Docs: add paragraph style #622

---

src/lib/app.css

Docs: add blockquote style #625

---

src/lib/app.css
src/routes/docs/[slug]/+page.svelte

Docs: fix left menu padding #627

---

src/routes/docs/[slug]/OnThisPage.svelte

Docs: Activate headings without comments in the menu #632

---

src/lib/app.css
src/routes/docs/[slug]/+page.svelte

Docs: Align the beginning of the main content #633

---

docs/20-development/10-vscode-extensions.md

Docs: Add Pretty TypeScript Errors to VSCode Extensions #640

---

.vscode/extensions.json

Add Pretty TypeScript Errors to extensions.json #641

---

src/routes/docs/[slug]/+page.svelte

Docs: Link to GitHub #649

---

docs/30-tests/10-vitest.md
docs/30-tests/20-playwright.md

Docs: Add "Check this file on GitHub" link #655

---

docs/30-tests/20-playwright.md
e2e/api/log.spec.ts
e2e/auth.setup.ts
e2e/chat.spec.ts
e2e/lib/setup.ts
e2e/main.spec.ts
e2e/translate.spec.ts
playwright.config.ts

Change web server settings on playwright config #658

---

docs/30-code-style/10-tsconfig.md

Docs: tsconfig #664

---

docs/30-code-style/10-tsconfig.md
docs/30-code-style/20-prettier.md
docs/30-code-style/30-eslint.md

Docs: Correct English

---

docs/30-code-style/20-prettier.md
docs/40-testing/10-vitest.md
docs/40-testing/20-playwright.md

Docs: Revise "testing" section's English #669

---

docs/20-development/20-sveltekit.md

Docs: SvelteKit #671

---

src/routes/docs/search_modale.svelte

Docs: search #606 fix scroll

---

src/routes/docs/search_modale.svelte

Docs: search #606 add keydown at search result

---

src/routes/docs/search_modale.svelte

Docs: Search results scroll with keydown #676

---

src/lib/app.css

Add border to glass panel #603

---

src/routes/(authed)/translate/+page.svelte

Tranlate: fix history caption position #624

---

.github/ISSUE_TEMPLATE/custom.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Write templates #703 Update issue templates

---

.github/ISSUE_TEMPLATE/custom.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Correct English in the templates #705

---

.github/pull_request_template.md

Update PR template #718

---

src/routes/+layout.svelte

Docs: Make new function from afterNavigate #685

---

src/routes/docs/search-modale.svelte

Docs: Change design of search result window #691

---

src/routes/docs/search-modale.svelte

Docs: Add ESC button to search result window #692

---

package-lock.json
package.json
src/lib/view/modifier_key.ts
src/lib/view/os_info.ts
src/routes/docs/side-bar.svelte

Docs: Change design of search box #688

---

src/routes/docs/[slug]/+page.svelte

Docs: Fix mobile second header text not updating #699

---

e2e/docs.spec.ts
src/lib/components/navbar.svelte
src/routes/docs/+layout.svelte

Docs: Add functionality to search button on navbar #710

---

src/routes/docs/side-bar.svelte

Docs: Fix padding-left of sidebar sections #737

---

src/routes/docs/search-modale.svelte

Docs: Refactor function set_scroll_result #726

---

.github/workflows/ci.yml
.husky/pre-push
.vscode/settings.json
docs/20-development/40-git-hooks.md
docs/40-testing/20-playwright.md
e2e/auth.setup.ts
e2e/docs.spec.ts
playwright.config.ts
src/hooks.server.ts

Run Playwright's tests in CI #741

---

src/routes/docs/[slug]/+page.svelte

Docs: Apply styles to inline code #747

---

e2e/chat.spec.ts
src/routes/(authed)/chat/[[room_id]]/+page.server.ts
src/routes/(authed)/chat/[[room_id]]/+page.svelte

Chat by room #448

---

docs/20-dev-environment/60-customize-zsh.md
e2e/docs.spec.ts

Docs: zsh #763

---

docs/50-testing/20-playwright.md
e2e/chat.spec.ts
src/routes/(authed)/chat/[[room_id]]/+page.svelte

Chat: Use root for room #770

---

.env.example

Update .env.example #780

---

package-lock.json
package.json
vite.config.ts

Remove warning on build #601

---

src/routes/docs/search-modale.svelte

Docs: Search box size #733

---

src/hooks.server.ts
src/lib/network/client_hostnames.ts
src/routes/api/log/+server.ts

Get hostname #506

---

src/routes/(authed)/chat/[[room_id]]/+page.svelte

Chat: Make top bar as tall as the name input field #769

---

src/routes/(authed)/chat/[[room_id]]/+page.svelte

Chat: Fix clicking new room button twice #792

---

src/routes/(authed)/chat/[[room_id]]/+page.svelte

Chat: Fix error when leave room without chat log #768

---

e2e/docs.spec.ts

Playwright: Increase timeout at access-next-pages #800

---

src/routes/docs/search-modale.svelte

Docs: Fix behavior when entering TAB key on search window #736

---

src/routes/docs/+layout.svelte
src/routes/docs/search-modale.svelte

#695: Docs: Show previous search result

---

docs/50-testing/10-vitest.md
docs/50-testing/20-playwright.md
e2e/auth.setup.ts
e2e/main.spec.ts
playwright.config.ts

Docs: Update tests #815

---

docs/50-testing/20-playwright.md

Docs: Fix playwright #826

---

docs/20-dev-environment/70-assets.md

Docs: Assets: Pixels #819

---

src/routes/docs/search-modale.svelte

Docs: Add reset button to search window #694

---

src/routes/docs/+layout.svelte
src/routes/docs/search-modale.svelte

Docs: Search by selected words when opened #696

---

docs/40-testing/10-vitest.md
docs/50-git/20-git-hooks.md

Docs: Add Installation #821

---

docs/60-team-sinproject/10-our-policy.md
docs/60-team-sinproject/meta.json

Docs: Our Policy #818

---

docs/20-dev-environment/30-vscode-extensions.md

Docs: Add extensions code link #835

---

docs/30-code-style/30-eslint.md

ESLint for SvelteKit #844

---

docs/30-code-style/40-stylelint.md

Docs: Stylelint #847

---

docs/60-team-sinproject/20-docs-history.md

Docs: History #843

---

docs/40-testing/10-vitest.md
e2e/translate.spec.ts
tsconfig.json
vite.config.ts

Update vite.config.ts #849

---

src/lib/components/navbar.svelte

Show app icon on NavBar #855

---

docs/20-dev-environment/20-vscord-workspace-settings.md
docs/20-dev-environment/30-vscode-extensions.md
docs/30-code-style/10-tsconfig.md
docs/30-code-style/20-prettier.md
docs/30-code-style/30-eslint.md
docs/30-code-style/40-stylelint.md
docs/40-testing/10-vitest.md
docs/40-testing/20-playwright.md
docs/50-git/20-git-hooks.md
docs/50-git/30-github-actions.md
src/lib/docs/markdown.ts
src/routes/docs/[slug]/+page.svelte

Docs: Show code title #857

---

src/lib/docs/markdown.ts
src/routes/docs/[slug]/+page.svelte

Docs: Add link to code title #858

---

docs/20-dev-environment/20-vscord-workspace-settings.md
docs/20-dev-environment/30-vscode-extensions.md
docs/30-code-style/10-tsconfig.md
docs/30-code-style/20-prettier.md
docs/30-code-style/30-eslint.md
docs/30-code-style/40-stylelint.md
docs/40-testing/10-vitest.md
docs/40-testing/20-playwright.md
docs/50-git/20-git-hooks.md
docs/50-git/30-github-actions.md
src/lib/docs/markdown.ts
src/routes/docs/[slug]/+page.svelte

Docs: Add GitHub icon to code title #859

---

docs/20-dev-environment/60-customize-zsh.md

Docs: Update Customize Zsh #820

---

src/lib/components/icons/copy_icon.svelte
src/lib/docs/markdown.ts
src/routes/docs/[slug]/+page.svelte

Docs: Fix code title link area #864

---

docs/50-git/20-git-hooks.md

Docs: fix code links #866

---

src/lib/docs/markdown.ts
src/routes/docs/[slug]/+page.svelte

Docs: Show copy button #830

---

src/routes/(authed)/chat/[[room_id]]/+page.svelte

Chat: Show icon for each message #813

---

docs/60-team-sinproject/30-slack.md

Docs: Slack #774

---

docs/50-git/10-git-branches-and-commits.md
src/lib/app.css
src/lib/components/icons/terminal_icon.svelte
src/lib/docs/markdown.ts
src/routes/docs/[slug]/+page.svelte

Docs: Display the copy button and title in the shell command block #873

---

src/lib/assets/search_index.json
src/lib/docs/search.ts
src/lib/docs/search_index.ts
src/routes/docs/search-modale.svelte

Docs: Show H2 headings in search #693

---

package-lock.json
src/lib/view/log/web_logger.ts

Fix an issue that caused an error when the browser is offline #881

---

src/routes/docs/search-modale.svelte

Docs: Fix scroll on search modale #884

---

src/routes/docs/side-bar.svelte

Docs: Align the height position of the search box #877

---

docs/40-testing/20-playwright.md
e2e/docs.spec.ts
playwright.config.ts
src/lib/docs/markdown.ts
src/routes/docs/[slug]/+page.svelte

Fix: marge markdown.ts #894

---

docs/30-code-style/30-eslint.md
docs/40-testing/10-vitest.md
docs/40-testing/20-playwright.md
docs/50-git/30-github-actions.md

Docs: Add links #829

---

.vscode/settings.json
docs/10-getting-started/20-creating-a-project.md
docs/50-git/20-git-hooks.md
server/server.md

Change the settings of Markdownlint #901

---

src/lib/app.css
src/lib/components/navbar.svelte
src/routes/docs/[slug]/+page.svelte

Docs: Fix navigation color on header and footer #905

---

docs/60-team-sinproject/10-our-team-policy.md

Docs: Update our team policy #895

---

src/routes/(authed)/chat/[[room_id]]/+page.svelte

Chat: Change the text y-position on new room button #890

---

src/hooks.server.ts
src/lib/network/client_hostname.ts
src/routes/api/log/+server.ts

About hostname #880

---

src/routes/docs/[slug]/+page.svelte

Docs: Fix an issue of screen text vertical position shifting when hovering #891

---

src/routes/docs/+layout.svelte

Docs: Fix height of side bar #921

---

src/lib/docs/search_index.ts

Docs: Fix creating search_index.json #904

---

src/lib/docs/markdown.ts

Docs: Fix copy button to match the style of the existing button #925

---

src/routes/docs/side-bar.svelte

Docs: Fix menu y-position #931

---

src/routes/docs/+layout.svelte
src/routes/docs/mobile-side-bar.svelte
src/routes/docs/side-bar.svelte

Docs: Animation for mobile sidebar #876

---

src/lib/app.css
src/routes/(authed)/chat/[[room_id]]/+page.svelte

Chat: Top bar roundness #823

---

package-lock.json
package.json

Update version to 0.38.0 #934

---

src/routes/docs/+layout.svelte

Upgrade svg animation #938

---

src/routes/(authed)/+page.svelte
src/routes/(authed)/chat/[[room_id]]/+page.svelte

Chat: Remove empty scrollbar #907

---

src/routes/(authed)/profile/+page.svelte

Profile: Save PNGs #771

---

src/lib/docs/markdown.ts
src/routes/docs/+layout.svelte
src/routes/docs/[slug]/+page.svelte
src/routes/docs/[slug]/OnThisPage.svelte

Docs: Add slide fade in animation #945

---

src/lib/components/translate/translate_box.svelte

translate: Increase spacing between X button and text area #327

---

.vscode/settings.json
docs/20-dev-environment/20-vscode-workspace-settings.md
docs/50-git/60-git-for-windows.md

Add an Eol setting to workspace settings #896

---

docs/20-dev-environment/80-chatgpt-prompts.md

Docs: ChatGPT Prompts #775

---

src/lib/components/snackbar.svelte
src/routes/(authed)/translate/+page.svelte

Docs: Fix snackbar x-position #927

---

src/lib/app.css
src/routes/(authed)/chat/[[room_id]]/+page.svelte

Decrease glass transparency #594

---

src/lib/components/nav_item.svelte
src/lib/components/nav_item_tab.svelte
src/lib/components/navbar.svelte
src/lib/components/tab.svelte

Draw an underline on the active tab #985

---

docs/20-dev-environment/80-chatgpt-prompts.md
docs/50-git/10-github-issues.md
docs/50-git/20-github-pull_requests.md
docs/60-team-sinproject/10-our-team-policy.md
src/lib/assets/search_index.json

Docs: Correct English #990

---

docs/40-testing/20-playwright.md
playwright.config.ts

Allow more workers during CI #997

---

docs/50-git/50-github-actions.md

Docs: Secrets for GitHub Actions #991

---

src/routes/docs/[slug]/+page.svelte

Docs: Fix highlighting code blocks #1002

---

src/routes/docs/audio.svelte

Change sound volume #979

---

docs/50-git/30-git-branches-and-commits.md
package.json
src/lib/git/create_git_branch.ts

Create branch script #992

---

docs/40-testing/20-playwright.md
playwright.config.ts
src/lib/api/api_path.test.ts
src/routes/docs/[slug]/+page.svelte
svelte.config.js

Comment out subdomain setting #980

---

.gitignore
docs/60-server/10-pm2.md
ecosystem.config.cjs

Server: setup pm2 #1011

---

src/routes/(authn)/pin-code/+page.server.ts

Refactor: wait and sleep method #883

---

src/routes/(authed)/chat/[[room_id]]/+page.svelte

Align the vertical and horizontal margins inside the window #973

---

src/routes/(authed)/chat/[[room_id]]/+page.svelte

Fix chat margins #1021

---

src/lib/app.css
src/lib/components/animation_switcher.svelte
src/lib/components/icons/moon_icon.svelte
src/lib/components/icons/pause_icon.svelte
src/lib/components/icons/play_icon.svelte
src/lib/components/navbar.svelte
src/lib/components/theme_switcher.svelte
src/lib/view/animation_store.ts
src/routes/docs/+layout.svelte

Docs: Add an animation toggle #955

---

prisma/migrations/20230604160418_943_profile_ext/migration.sql
prisma/schema.prisma
src/lib/auth/user_repository.ts
src/lib/auth/user_repository_prisma.ts
src/lib/avatar/avatar.ts
src/lib/avatar/avatar_file_path.ts
src/routes/(authed)/profile/+page.server.ts
src/routes/api/avatar/[user_id=user_id]/+server.ts

Profile: DB Integration #943

---

src/lib/app.css
src/lib/docs/markdown.ts

CSS-Refactor: Adjust color on hovered copy button #967

---

src/lib/app.css
src/routes/+layout.svelte

Change design to be more like the tailwind documentation design #582

---

src/routes/(authed)/+page.svelte
src/routes/(authed)/chat/[[room_id]]/+page.svelte
src/routes/(authed)/translate/+page.svelte

Fix background color of language list on windows #959

---

src/lib/components/navbar.svelte
src/lib/view/animation_store.ts
src/routes/docs/+layout.svelte

Docs: Disabling animation and reenabling causes error #1041

---

src/lib/app.css

Header: Fix hovered icon color #1046

---

src/lib/app.css

Light-Theme: Adjust background color on copy button #1049

---

src/lib/docs/markdown.ts
src/routes/docs/[slug]/+page.svelte
src/routes/docs/[slug]/on_this_page.svelte
src/routes/docs/side_bar.svelte

Docs: Adjust hovered link-text color on light-theme #1048

---

src/routes/(authed)/chat/[[room_id]]/+page.svelte

Chat: Fix text position of new room button #1047

---

vite.config.ts

Fix build error for .prisma/client/index-browser #1065

---

e2e/auth.setup.ts
e2e/chat.spec.ts
e2e/main.spec.ts
e2e/translate.spec.ts
package-lock.json
package.json
src/lib/app/app.ts
src/lib/auth/pin_code.ts
src/lib/auth/pin_code_mailer.ts
src/lib/components/navbar.svelte
src/lib/components/version_footer.svelte
src/routes/(authed)/+page.svelte
src/routes/(authed)/chat/[[room_id]]/+page.svelte
src/routes/(authed)/profile/+page.svelte
src/routes/(authed)/translate/+page.svelte
src/routes/(authn)/pin-code/+page.svelte
src/routes/(authn)/sign-in/+page.svelte
src/routes/docs/[slug]/+page.svelte

Create footer component #1067

---

src/lib/components/nav_item.svelte

Fix: changing language on navbar #1070

---

src/lib/components/navbar.svelte
src/lib/git/create_git_branch.ts
src/routes/(authed)/chat/[[room_id]]/+page.svelte

Don't change navbar language on chat page #1072

---

package-lock.json
package.json
src/lib/git/create_git_branch.ts

Release v0.39.0 #1075

---

src/app.html
src/hooks.server.ts
src/lib/components/navbar.svelte
src/lib/components/theme_switcher.svelte
src/lib/stores.ts
src/routes/+layout.svelte
src/routes/+layout.ts

Allow changing theme without logging in #1045

---

src/routes/docs/[slug]/+page.svelte

Apply theme to code block #1057

---

src/routes/+layout.svelte

Center background image vertically #1053

---

src/lib/components/version_footer.svelte

Set document link style on footer #1077

---

src/routes/docs/search_modale.svelte

Docs: Search box animation #986

---

src/routes/docs/+layout.svelte
src/routes/docs/search_modale.svelte

Fix: Allow scrolling after closing search modal with shortcut key #1092

---

docs/20-dev-environment/90-tailwind-css.md

Docs: tailwind #987

---

docs/10-getting-started/10-introduction.md
docs/20-dev-environment/80-chatgpt-prompts.md
docs/20-dev-environment/90-warp.md
docs/30-code-style/50-style-guide.md
src/lib/assets/search_index.json
src/routes/docs/[slug]/+page.svelte

Adjust Docs content #1105

---

package-lock.json
package.json

Release v0.40.0 #1107

---

.github/ISSUE_TEMPLATE/release.md

Create issue template for release #1115

---

.github/ISSUE_TEMPLATE/release.md
package-lock.json
package.json

Release v0.41.0 #1117

---

static/sitemap.xml

Create an robots.txt file #1122

---

package-lock.json
package.json

Release v0.42.0 #1127

---

package-lock.json
package.json

Release v0.43.0 #1133

---

package-lock.json
package.json
static/sitemap.xml

Recreate an sitemap.xml #1132

---

src/routes/+page.svelte

Lighthouse: Ensure text remains visible during webfont load #1139

---

.vscode/settings.json
docs/20-dev-environment/30-vscode-extensions.md
docs/60-server/30-caddy.md
rest/test.rest

Lighthouse: Serve static assets with an efficient cache policy #1144

---

package-lock.json
package.json

Release v0.44.0 #1152

---

docs/20-dev-environment/30-vscode-workspace-extensions.md

Docs: VSCode Workspace Extensions #1143

---

docs/20-dev-environment/10-macos-settings.md

Docs: Update macOS Settings #1141

---

docs/50-git/30-git-branches-and-commits.md

Add a link to the create-branch script #1120

---

src/lib/app.css

Docs: Safari style adjustment

---

docs/10-getting-started/30-app-structure.md

Fix: links on App Structure #1110

---

package-lock.json
package.json

Release v0.45.0 #1172

---

e2e/chat.spec.ts
e2e/learn.spec.ts
e2e/translate.spec.ts
package-lock.json
package.json
src/lib/components/nav_item.svelte
src/routes/(authed)/learn/+page.svelte
src/routes/(authed)/translate/+page.svelte
src/routes/+layout.ts

Fix locale not updating on refresh on main, chat, docs, and profile #1174

---

src/routes/(authed)/translate/+page.svelte

Translation: Make the swap button pressable #1176

---

package-lock.json
package.json

Release v0.46.0 #1183

---

src/lib/app.css

Docs: Fix sytles #1185

---

src/routes/+layout.svelte

When the theme is changed twice, the second update is not sent to server #1179

---

.vscode/settings.json
docs/20-dev-environment/15-chrome-extensions.md
docs/20-dev-environment/30-vscode-workspace-extensions.md

Docs: Chrome Extensions #1177

---

docs/30-code-style/50-style-guide.md

Docs: Remove link on async example #1196

---

docs/20-dev-environment/90-tailwind-css.md

Docs: Write tailwind configuration #1180

---

docs/20-dev-environment/70-assets.md

Docs: Add DaFont to Assets page #1188

---

.vscode/settings.json
docs/20-dev-environment/70-assets.md

Docs: spelling correction of Pixels on Assets page #1194

---

package-lock.json
package.json

Release v0.47.0 #1201

---

.github/ISSUE_TEMPLATE/release.md

Update release template #1203

---

package.json

Create search-index on preBuild #1204

---

package-lock.json
package.json

Release v0.47.1 #1207

---

src/routes/docs/[slug]/+page.svelte

Adjust footer text layout #1213

---

LICENSE
src/lib/app/app.ts
src/lib/components/version_footer.svelte
src/routes/docs/[slug]/+page.svelte

Show copyright #1220

---

src/lib/docs/markdown.ts
src/routes/docs/+layout.server.ts
src/routes/docs/[slug]/+page.server.ts

Adjust category title cases #1217

---

.github/ISSUE_TEMPLATE/release.md

Release v0.48.0 #1225

---

package-lock.json
package.json
static/robots.txt
static/sitemap.xml

Update an sitemap.xml file and an robots.txt file #1229

---

src/lib/components/navbar.svelte
src/lib/stores.ts
src/routes/docs/+layout.svelte

Docs: Display icons when first navigating on mobile devices #1146

---

src/lib/components/menu_items_sub.svelte

Change text color on right menu #1218

---

package-lock.json
package.json

Release v0.49.0 #1237

---

package-lock.json
package.json
src/lib/app.css

Docs: Equipments: Fix image aspect ratio #1241

---

.vscode/settings.json
docs/60-server/50-ngrok.md

Docs: ngrok #1242

---

package-lock.json
package.json

Release v0.50.0 #1250

---

.github/ISSUE_TEMPLATE/release.md
docs/60-server/40-updating-the-server.md
src/lib/assets/search_index.json

Delete @ in Release template #1252

---

docs/20-dev-environment/40-global-npm-packages.md
docs/20-dev-environment/41-npm-check-updates.md
package-lock.json
package.json
static/sitemap.xml

Docs: ncu #1245

---

docs/30-assets/20-jpg-png-to-avif.md
package-lock.json
package.json

Can I use AVIF #1263

---

docs/30-assets/20-jpg-png-to-avif.md
docs/30-assets/30-ttf-to-woff2.md
package-lock.json
package.json

Docs: Can I use WOFF2 #1267

---

package-lock.json
package.json
static/manifest.json

Use maskable icons for PWA #1270

---

package-lock.json
package.json
static/manifest.json

Change PWA base color #1268

---

e2e/docs.spec.ts
src/lib/components/icons/sign_in_icon.svelte
src/lib/components/menu_items_sub.svelte
src/lib/components/mobile_menu_bar.svelte
src/lib/components/navbar.svelte

Change top menu and left menu items #1273

---

src/app.html

Pass lighthouse pwa tests #1277

---

src/lib/components/social_meta_tags.svelte
src/routes/(authed)/chat/[[room_id]]/+page.svelte
src/routes/(authed)/learn/+page.svelte
src/routes/(authed)/profile/+page.svelte
src/routes/(authed)/translate/+page.svelte
src/routes/(authn)/pin-code/+page.svelte
src/routes/(authn)/sign-in/+page.svelte
src/routes/+page.svelte
src/routes/docs/[slug]/+page.svelte

Implement Open Graph Protocol and Twitter Card metatags #1283

---

package-lock.json
package.json

Release v0.54.0

---

docs/35-clean-code/40-objects-and-data-structures.md
docs/35-clean-code/80-comments.md

Docs: Clean code #1290

---

docs/60-server/30-caddy.md
rest/test.rest

Add png to cache type #1289

---

package-lock.json
package.json

Release 0.55.0

---

docs/35-clean-code/15-format.md
docs/35-clean-code/16-quarity.md
docs/50-git/30-git-branches-and-commits.md

Docs: Update clean code #1301

---

docs/30-assets/10-assets.md

Docs: Add free image sites to Assets #1299

---

docs/20-dev-environment/50-sveltekit.md

Docs: Creating a Project with SvelteKit #1297

---

docs/50-git/30-git-branches-and-commits.md
package.json

Change npm run create-branch to npm run branch #1305

---

docs/50-git/30-git-branches-and-commits.md

Docs: Change Git Branches example #1310

---

.github/ISSUE_TEMPLATE/release.md
docs/35-clean-code/15-format.md
docs/35-clean-code/17-quality.md
docs/35-clean-code/30-functions.md
docs/60-server/40-updating-the-server.md

Docs: Update clean code #1309

---

src/routes/docs/[slug]/+page.svelte

Docs: Change the scope of the link #1329

---

package-lock.json
package.json

Release 0.59.0

---

docs/10-company-information/10-portfolio.md
docs/10-company-information/20-about.md

Docs: Portfolio and about translation check #1337

---

docs/30-clean-code/15-format.md
docs/35-code-style/30-eslint.md

Docs: Fix English #1341

---

.github/ISSUE_TEMPLATE/custom.md
.github/pull_request_template.md

Update issue templates #1339

---

.eslintrc.cjs
.vscode/settings.json

Add the tabsize rule #1343

---

package-lock.json
package.json

Release 0.60.0

---

e2e/chat.spec.ts
e2e/translate.spec.ts
src/lib/components/translate/translate_box.svelte
src/lib/view/event_key.ts
src/routes/(authed)/chat/[[room_id]]/+page.svelte

Chat: Change key binds #1325

---

package-lock.json
package.json

Release 0.61.0

---

.github/workflows/cr-akiojin-gpt-4.yml
src/routes/+page.svelte

Change akiojin code review CI to GPT4s #1374

---

playwright.config.ts
src/lib/auth/email.ts
src/lib/auth/pin_code.ts

1382 fix the security hotspots pointed out by sonarcloud

---

playwright.config.ts

Fix the security hotspots pointed out by SonarCloud #1388

---

README.md
playwright.config.ts

Modify the Creating a Project link #1387

---

.github/pull_request_template.md

Update PR template #1391

---

.vscode/settings.json
playwright.config.ts
src/lib/components/menu_items_sub.svelte
src/lib/components/version_footer.svelte
src/routes/+page.svelte

Strengthen eslint rules #1377

---

.github/pull_request_template.md

Update PR Template #1402

---

.vscode/extensions.json

Update extensions.json #1398

---

.github/workflows/ci.yml

Update ci.yml #1400

---

svelte.config.js

Change fs.readFileSync() to fs.promises.readFile() #1256

---

.github/ISSUE_TEMPLATE/custom.md

Update Issue Template #1433

---

.husky/pre-commit

Prevent commits directory to main branch

---

.github/ISSUE_TEMPLATE/custom.md
.github/pull_request_template.md

Delete "share screen", "start task comment on slack" on Issue and PR template #1439

---

.github/pull_request_template.md

PR Template Modify who can merge into main branch #1443

---

src/lib/api/api_path.test.ts
src/lib/app/app_setting_repository.test.ts
src/lib/app/repository.test.ts
src/lib/auth/auth_pin_repository.test.ts
src/lib/auth/email.test.ts
src/lib/auth/life_time.test.ts
src/lib/auth/mail_subject.test.ts
src/lib/auth/pin_code.test.ts
src/lib/auth/user_repository.test.ts
src/lib/chat/chat_locale_code.test.ts
src/lib/chat/chat_log_repository.test.ts
src/lib/chat/chat_message.test.ts
src/lib/chat/chat_name.test.ts
src/lib/chat/chat_room_id.test.ts
src/lib/general/valid_id.test.ts
src/lib/general/valid_key.test.ts
src/lib/locale/locale_code.test.ts
src/lib/locale/locale_repository.test.ts
src/lib/speech/sound/sound_repository.test.ts
src/lib/speech/voice/voice_repository.test.ts
src/lib/text/delete_text_api.test_.ts
src/lib/text/texts_api.test_.ts

Use it() function on Vitest code #1455

---

.github/workflows/ci.yml
.vscode/settings.json
sonar-project.properties

Activate SonarCloud coverage #1452

---

vite.config.ts

Configure SonarCloud Test Coverage #1459

---

.github/workflows/ci.yml
package-lock.json
package.json
vite.config.ts

Configure SonarCloud Test Coverage - Part2(#1459) #1463
